name: Demo Github Action
'on':
    pull_request:
        branches:
            - master
        types:
            - opened
            - closed
    push:
        tags:
            - 'v*.*.*'
jobs:
    test:
        runs-on: ubuntu-22.04
        container:
            image: 'node:18'
        env:
            PORT: ${{ vars.PORT }}
            APP_KEY: ${{ vars.APP_KEY }}
            DRIVE_DISK: ${{ vars.DRIVE_DISK }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Install & Tests
                run: npm install && npm test

    delivery:
        runs-on: ubuntu-22.04
        needs: test
        env:
            IMAGE_NAME: '${{ vars.IMAGE_NAME }}'
            IMAGE_VERSION: $GITHUB_SHA
        steps:
            -   uses: actions/checkout@v2
            -   name: Docker Login
                run: >-
                    docker login -u ${{ secrets.DOCKER_USER }} -p ${{
                    secrets.DOCKER_PASSWORD }}
            -   name: Set Name and Version for Dev and Staging
                if: ${{ github.event_name == 'pull_request' }}
                run: |
                    echo "IMAGE_NAME=${{ env.IMAGE_NAME }}-dev" >> $GITHUB_ENV
            -   name: Set Name and Version for Production
                if: startsWith(github.ref, 'refs/tags/v')
                run: |
                    echo "IMAGE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            -   name: Print Name and Version
                run: 'echo "${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"'
#            -   name: Docker Build
#                run: 'docker build -t ${{ env.IMAGE_NAME }} .'
#            -   name: Docker Tag
#                run: >
#                    docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
#
#                    docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
#            -   name: Docker Push
#                run: >
#                    docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
#
#                    docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest

    release:
        runs-on: ubuntu-22.04
        needs: delivery
        if:  github.ref == 'refs/head/release/dev'
        steps:
            - name: Print Release
              run: echo "This is a release to dev"

    deploy-dev:
        runs-on: ubuntu-22.04
        needs: delivery
        if: ${{ github.event_name == 'pull_request' }}
        environment:
            name: Dev
            url: 'https://environment.dev'
        steps:
            -   name: Deploy
                run: echo "Deploy in Dev!"
    e2e-dev:
        runs-on: ubuntu-22.04
        needs: deploy-dev
        environment: Dev
        steps:
            -   name: E2E Test
                run: echo "E2E Test in Dev!"

    deploy-staging:
        runs-on: ubuntu-22.04
        needs: e2e-dev
        if: github.event.pull_request.merged == true
        environment:
            name: Staging
            url: 'https://environment.dev'
        steps:
            -   name: Deploy
                run: echo "Deploy in Staging!"

    e2e-staging:
        runs-on: ubuntu-22.04
        needs: deploy-staging
        environment: Staging
        steps:
            -   name: E2E Test
                run: echo "E2E Test in Staging!"
