name: Demo Github Action

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: github-action-demo-api
  IMAGE_VERSION: ${{ vars.IMAGE_VERSION }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    container:
      image: node:18
    steps:
      - uses: actions/checkout@v2
      - name: Install & Tests
        run: npm install && npm test

  cd:
    runs-on: ubuntu-22.04
    needs: ci
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Print Name and Version
        run: echo "${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"
      - name: Docker Build
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Docker Tag
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
